# Generated by Django 5.2.17 on 2026-09-15 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('assets', '0001_initial'),
        ('ingest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('side', models.CharField(choices=[('BUY', '买入'), ('SELL', '卖出'), ('DIVIDEND', '分红/利息'), ('DEPOSIT', '入金'), ('WITHDRAW', '出金'), ('FEE', '费用'), ('TAX', '税费'), ('SPLIT', '拆分/送股')], max_length=16, verbose_name='方向')),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='数量')),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='单价')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='现金变动')),
                ('fee', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='手续费')),
                ('tax', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='税费')),
                ('currency', models.CharField(default='CNY', max_length=8, verbose_name='币种')),
                ('fx_rate', models.DecimalField(decimal_places=8, default=1, max_digits=20, verbose_name='入账汇率')),
                ('traded_at', models.DateTimeField(verbose_name='发生时间')),
                ('source', models.CharField(choices=[('MANUAL', '手动'), ('AGENT', 'Agent 识别'), ('IMPORT', '导入')], default='MANUAL', max_length=16, verbose_name='来源')),
                ('client_request_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='幂等键')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.account', verbose_name='账户')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='assets.asset', verbose_name='标的')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='ingest.evidence', verbose_name='原始凭证')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '流水',
                'verbose_name_plural': '流水',
                'ordering': ('-traded_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DividendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ex_date', models.DateField(blank=True, null=True, verbose_name='除权日')),
                ('pay_date', models.DateField(blank=True, null=True, verbose_name='派息日')),
                ('amount_per_share', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='每股派息')),
                ('shares', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='持股数')),
                ('gross', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='税前')),
                ('tax', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='税费')),
                ('net', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='税后')),
                ('currency', models.CharField(default='CNY', max_length=8, verbose_name='币种')),
                ('reinvested', models.BooleanField(default=False, verbose_name='分红再投')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dividends', to='accounts.account', verbose_name='账户')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dividends', to='assets.asset', verbose_name='标的')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dividend', to='transactions.transaction', verbose_name='关联流水')),
            ],
            options={
                'verbose_name': '股息记录',
                'verbose_name_plural': '股息记录',
                'ordering': ('-pay_date', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-traded_at'], name='transaction_user_id_99562a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'asset'], name='transaction_account_9ddf37_idx'),
        ),
        migrations.AddIndex(
            model_name='dividendrecord',
            index=models.Index(fields=['user', '-pay_date'], name='transaction_user_id_32baac_idx'),
        ),
    ]
