# Generated by Django 5.2.17 on 2026-09-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('symbol', models.CharField(max_length=32, verbose_name='代码')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='名称')),
                ('market', models.CharField(choices=[('A', 'A股'), ('HK', '港股'), ('US', '美股'), ('FUND', '基金'), ('CRYPTO', '数字货币'), ('FOREX', '外汇'), ('OTHER', '其他')], default='A', max_length=16, verbose_name='市场')),
                ('asset_type', models.CharField(choices=[('STOCK', '股票'), ('ETF', 'ETF'), ('BOND', '债券'), ('FUND', '基金'), ('CRYPTO', '数字货币'), ('FOREX', '外汇'), ('CASH', '现金'), ('OTHER', '其他')], default='STOCK', max_length=16, verbose_name='类型')),
                ('currency', models.CharField(default='CNY', max_length=8, verbose_name='计价货币')),
                ('is_dividend_asset', models.BooleanField(default=False, verbose_name='股息资产')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': '标的',
                'verbose_name_plural': '标的',
                'ordering': ('market', 'symbol'),
                'indexes': [models.Index(fields=['market', 'symbol'], name='assets_asse_market_ea1f7f_idx')],
                'unique_together': {('market', 'symbol')},
            },
        ),
    ]
