# Generated by Django 5.2.17 on 2026-09-15 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, verbose_name='账户名称')),
                ('broker', models.CharField(blank=True, max_length=64, verbose_name='机构')),
                ('market', models.CharField(choices=[('A', 'A股'), ('HK', '港股'), ('US', '美股'), ('FUND', '基金'), ('CRYPTO', '数字货币'), ('FOREX', '外汇'), ('OTHER', '其他')], default='A', max_length=16, verbose_name='市场')),
                ('account_type', models.CharField(choices=[('BROKER', '券商'), ('BANK', '银行'), ('CRYPTO', '交易所/钱包'), ('CASH', '现金'), ('OTHER', '其他')], default='BROKER', max_length=16, verbose_name='类型')),
                ('currency', models.CharField(default='CNY', max_length=8, verbose_name='本位币')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '账户',
                'verbose_name_plural': '账户',
                'ordering': ('-created_at',),
                'unique_together': {('user', 'name')},
            },
        ),
    ]
