# Generated by Django 5.2.17 on 2026-09-15 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='evidence/%Y/%m/', verbose_name='截图')),
                ('ocr_text', models.TextField(blank=True, verbose_name='识别原文')),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='文件指纹')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '原始凭证',
                'verbose_name_plural': '原始凭证',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IngestJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('IMAGE', '截图'), ('TEXT', '文本')], default='IMAGE', max_length=16, verbose_name='类型')),
                ('raw_text', models.TextField(blank=True, verbose_name='原始文本')),
                ('status', models.CharField(choices=[('PENDING', '处理中'), ('SUCCEEDED', '成功'), ('FAILED', '失败')], default='PENDING', max_length=16, verbose_name='状态')),
                ('result_json', models.JSONField(blank=True, default=dict, verbose_name='抽取结果')),
                ('confidence', models.FloatField(default=0, verbose_name='置信度')),
                ('missing', models.JSONField(blank=True, default=list, verbose_name='缺失字段')),
                ('error', models.TextField(blank=True, verbose_name='错误信息')),
                ('client_request_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='幂等键')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认入账时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='ingest.evidence', verbose_name='凭证')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_jobs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '抽取任务',
                'verbose_name_plural': '抽取任务',
                'ordering': ('-created_at',),
            },
        ),
    ]
