# Generated by Django 5.2.17 on 2026-09-15 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=8, verbose_name='源币种')),
                ('quote', models.CharField(max_length=8, verbose_name='目标币种')),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='汇率')),
                ('date', models.DateField(verbose_name='日期')),
                ('source', models.CharField(default='', max_length=32, verbose_name='数据源')),
            ],
            options={
                'verbose_name': '汇率',
                'verbose_name_plural': '汇率',
                'ordering': ('-date',),
                'unique_together': {('base', 'quote', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PriceQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='价格')),
                ('currency', models.CharField(default='CNY', max_length=8, verbose_name='币种')),
                ('change_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='涨跌幅%')),
                ('source', models.CharField(default='', max_length=32, verbose_name='数据源')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='抓取时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='assets.asset', verbose_name='标的')),
            ],
            options={
                'verbose_name': '行情快照',
                'verbose_name_plural': '行情快照',
                'ordering': ('-fetched_at',),
                'indexes': [models.Index(fields=['asset', '-fetched_at'], name='market_pric_asset_i_f90ea7_idx')],
            },
        ),
    ]
